--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElectroGamesDev/BankUI
build-by-default: true
branches:
- main
projects:
  BankUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.0.0
    - src: poggit/libasynql/libasynql
      version: ^4.0.1
...
