# [FORKED] A BankUI Plugin For PocketMine-MP
# Copyright (C) 2021 ElectroGamesYT, KygekDev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

main : Electro\BankUI\BankUI
name: BankUI
version: 2.0.0
api: 3.0.0
authors:
- Electro
- KygekDev
depend: ["EconomyAPI"]

commands:
  bank:
    description: Opens The BankUI