main : Electro\BankUI\BankUI
name: BankUI
version: 4.0.3
api: 5.0.0
Author: Electro
depend: ["BedrockEconomy"]

commands:
  bank:
    description: Opens The BankUI
    usage: /bank
    permission: bankui.cmd
    
permissions:
  bankui.admin:
    description: Permission to manage other players bank
    default: op
  bankui.admin.backup:
    description: Permission to backup data
    default: op
  bankui.admin.migrate:
    description: Permission to migrate data
    default: op
  bankui.cmd:
    description: Permission to open bank ui
    default: true
